### ISSUE TITLE
Error with Step 3 of account setup (account-setup.md)

### ISSUE THREAD

**Issue by bhk1019** [university-bootcamp/coding-environment#12]
There is an error that students have been frequently encountering when trying to link their Github accounts as in Step 3 of `account-setup.md`.

The error arises when students try to run the following command:
```
curl https://raw.githubusercontent.com/university-bootcamp/coding-environment/cloud-ide-instructions/github_auth.rb > ~/.bootcamp-github.rb && ruby ~/.bootcamp-github.rb
```
This is what the error message looks like:
https://imgur.com/a/AljB14c

So far, I have been sending students the following fix, which has been working successfully:

>Try the following steps:
>1) Run the command `gem install github_api` in your terminal.
>2) Once the install finishes, run `touch .bootcamp-github.rb`.
>3) That command should have made an empty file called `.bootcamp-github.rb`. Find this file and open it in your text editor. It should be a hidden file inside of the `coding-environment` folder. If you press `Command + Shift + .` on a Mac you can view hidden files in the Finder.
>4) Then, copy and paste the following into the empty `.bootcamp-github.rb` file:
```
require 'github_api'
require 'io/console'

# Bypass annoying deprecation warning between the
# github_api gem and the faraday gem
Faraday::Builder = Faraday::RackBuilder

print "Github Username: "
user_name = gets.strip
print "Github Password (nothing will be displayed):"
password  = STDIN.noecho(&:gets).strip
github = Github.new(:login => user_name, :password => password)
github.users.keys.create("title" => "FirehoseVagrant", 
    "key"=> File.open("/home/vagrant/.ssh/id_rsa.pub").read)
puts "\nok!"
```
>5) Once you do that, save the `.bootcamp-github.rb` file. In your terminal, run `ruby .bootcamp-github.rb`.

Is there any way this or another (possibly more elegant) fix can be incorporated into the instructions?

**Comment by bhk1019** [comment]
A student found a fix to this problem!!

Running `curl https://raw.githubusercontent.com/university-bootcamp/coding-environment/master/github_auth.rb > ~/.bootcamp-github.rb && ruby ~/.bootcamp-github.rb` instead of the one currently here: https://github.com/university-bootcamp/coding-environment/blob/master/account-setup.md#step-3-configure-github-with-ssh-key does the trick.

**Comment by bhk1019** [comment]
@ceckenrode , can you take a look at this most recent comment I added?

**Comment by PoffDev** [comment]
@ceckenrode @tteltrab @hsinkoff  Could we please please revisit this solution to be added? Out of 40 students that started last week, about 30 of them experienced an error with the current curl command.
