### ISSUE TITLE
Timeout Error When Creating Workspaces on Code Envy

### ISSUE THREAD

**Issue by PoffDev** [university-bootcamp/coding-environment#14]
Students are receiving this error when initially setting up codenvy:

![image](https://user-images.githubusercontent.com/16676081/55639570-b2071e80-5797-11e9-9598-80528567f697.png)

I would suggest a paragraph or two about how to fix it (if there is one, I'm stumped) Or a link to instructions to set up the environment locally.

**Comment by ceckenrode** [comment]
This should be resolved now @PoffDev
